version: "3.8"

services:
  transport_api_server:
    container_name: transport-api-server
    command: python manage.py runserver 0.0.0.0:${SERVER_PORT}
    tty: true
    build:
      context: ./transport_api
    volumes:
      - ./transport_api:/transport_api:cached
    restart: on-failure
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=transport-api-database
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - STAGE=docker
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

  db:
    container_name: transport-api-database
    command: -p ${DB_PORT}
    image: postgres:14-alpine
    volumes:
      - transport_api_db_storage:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  transport_api_db_storage: