# Generated by Django 4.1.3 on 2022-11-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(default="Client Name By Default", max_length=255),
                ),
                ("birth_date", models.DateField(null=True)),
                ("phone", models.CharField(default="80250000000", max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="Licenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.FloatField()),
                ("payload", models.IntegerField()),
                ("ship_date", models.DateField()),
                ("recovery_date", models.DateField()),
                ("shipment_price", models.FloatField()),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transport_api_server.clients",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Drivers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(default="Driver Name By Default", max_length=255),
                ),
                ("birth_date", models.DateField()),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transport_api_server.licenses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyCars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17)),
                ("model", models.CharField(max_length=255)),
                ("volume", models.FloatField()),
                ("payload", models.IntegerField()),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transport_api_server.licenses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarColumns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transport_api_server.companycars",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transport_api_server.drivers",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transport_api_server.orders",
                    ),
                ),
            ],
        ),
    ]
