# Generated by Django 4.1.3 on 2022-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transport_api_server",
            "0002_rename_carcolumns_ways_alter_clients_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companycars",
            options={
                "verbose_name": "Company Cars",
                "verbose_name_plural": "Company Cars",
            },
        ),
        migrations.AlterModelOptions(
            name="drivers",
            options={"verbose_name": "Drivers", "verbose_name_plural": "Drivers"},
        ),
        migrations.AlterModelOptions(
            name="licenses",
            options={"verbose_name": "Licenses", "verbose_name_plural": "Licenses"},
        ),
        migrations.RemoveField(
            model_name="orders",
            name="payload",
        ),
        migrations.AddField(
            model_name="orders",
            name="weight",
            field=models.IntegerField(default=100, verbose_name="Order weight in kg"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="volume",
            field=models.FloatField(verbose_name="Order volume in m3"),
        ),
    ]
