# Generated by Django 4.1.3 on 2022-12-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transport_api_server",
            "0003_alter_companycars_options_alter_drivers_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clients",
            options={
                "ordering": ("full_name",),
                "verbose_name": "Clients",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="drivers",
            options={
                "ordering": ("full_name",),
                "verbose_name": "Drivers",
                "verbose_name_plural": "Drivers",
            },
        ),
        migrations.AlterModelOptions(
            name="licenses",
            options={
                "ordering": ("category",),
                "verbose_name": "Licenses",
                "verbose_name_plural": "Licenses",
            },
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={
                "ordering": ("ship_date",),
                "verbose_name": "Orders",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterField(
            model_name="companycars",
            name="payload",
            field=models.IntegerField(verbose_name="Car maximum load in kg"),
        ),
        migrations.AlterField(
            model_name="companycars",
            name="volume",
            field=models.FloatField(verbose_name="Car trunk volume in m3"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="shipment_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
