# Generated by Django 4.1.3 on 2022-12-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transport_api_server",
            "0004_alter_clients_options_alter_drivers_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ways",
            new_name="Trips",
        ),
        migrations.AlterModelOptions(
            name="trips",
            options={"verbose_name": "Trips", "verbose_name_plural": "Trips"},
        ),
        migrations.AlterField(
            model_name="orders",
            name="shipment_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
