# Generated by Django 4.1.3 on 2022-12-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_api_server", "0005_rename_ways_trips_alter_trips_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="shipment_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Shipment price, BYN"
            ),
        ),
        migrations.AddConstraint(
            model_name="orders",
            constraint=models.CheckConstraint(
                check=models.Q(("recovery_date__gt", models.F("ship_date"))),
                name="mycustomconstraint_check1",
            ),
        ),
    ]
