# Generated by Django 4.1.3 on 2022-12-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transport_api_server",
            "0007_remove_orders_mycustomconstraint_check1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="volume",
            field=models.FloatField(verbose_name="Order volume, m^3"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="weight",
            field=models.IntegerField(verbose_name="Order weight, kg"),
        ),
    ]
