# Generated by Django 4.1.3 on 2022-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport_api_server", "0008_alter_orders_volume_alter_orders_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenses",
            name="max_weight",
            field=models.IntegerField(
                default=5000, verbose_name="Maximum car payload for given license, kg"
            ),
            preserve_default=False,
        ),
    ]
