# Generated by Django 4.1.3 on 2022-12-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport_api_server", "0009_licenses_max_weight"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompanyCars",
            new_name="Cars",
        ),
        migrations.AlterModelOptions(
            name="cars",
            options={"verbose_name": "Cars", "verbose_name_plural": "Cars"},
        ),
    ]
