# Generated by Django 4.1.3 on 2022-12-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport_api_server", "0010_rename_companycars_cars_alter_cars_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenses",
            name="max_weight",
        ),
    ]
