# Generated by Django 4.1.3 on 2022-12-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transport_api_server", "0011_remove_licenses_max_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="transport_api_server.licenses",
                verbose_name="Required license",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="payload",
            field=models.IntegerField(verbose_name="Car maximum load, kg"),
        ),
        migrations.AlterField(
            model_name="cars",
            name="volume",
            field=models.FloatField(verbose_name="Car trunk volume, m^3"),
        ),
        migrations.AlterField(
            model_name="clients",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clients",
            name="phone",
            field=models.CharField(max_length=11),
        ),
    ]
